name: <+service.name>
replicas: 5
image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>
namespace: <+infra.namespace>
serviceType: ClusterIP
servicePort: 80
serviceTargetPort: 5000
serviceAccount: true
ingressSubDomain: <+project.identifier>
env:
  config:
    APPLICATION_VERSION: v1.<+pipeline.sequenceId>
    SERVICE_NAME: <+service.name>
    LAST_EXECUTION_ID: <+pipeline.executionId>
    HARNESS_BUILD: <+pipeline.sequenceId>
    ARTIFACT_VERSION: <+artifact.image>
