name: <+service.name>
replicas: 1
image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>
namespace: <+infra.namespace>
#createNamespace: "true"
serviceType: ClusterIP
servicePort: 80
serviceTargetPort: 3000
ingressSubDomain: <+variable.sandbox_id>
